### PR TITLE
Modify access control for Extension

### PR DESCRIPTION
**Pull request by MarcSteven**

### CODE REVIEW

**Review by zhaomeiru66 — APPROVED** [review]
Well done!

**Comment by SlaunchaMan** [comment]
Can you re-indent the lines after these changes (highlight and press Control+I in Xcode)? Thanks for the contribution!

**Comment by SlaunchaMan** [comment]
This has been merged into 0.5.4!

**Review by SlaunchaMan — COMMENTED** [review]
👍

**Pull request closed without merging**
